packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"

yarnPath: .yarn/releases/yarn-4.0.0-rc.13.git.20220716.hash-b8d2315.cjs

changesetIgnorePatterns:
  - "**/__tests__/*.{js,ts}"
  - "packages/scripts/**/*"
