pnpMode: loose

packageExtensions:
  "debug@*":
    dependencies:
      supports-color: "*"
  "rollup-plugin-ts@*":
    peerDependencies:
      "@babel/plugin-syntax-dynamic-import": "*"

yarnPath: .yarn/releases/yarn-sources.cjs
