name: ci

env:
  DEBUG: napi:*
  MACOSX_DEPLOYMENT_TARGET: "10.13"

"on":
  push:
    branches:
      - main
      - dev
    tags-ignore:
      - "**"
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
  pull_request_target:
    types:
      - labeled
  repository_dispatch: null

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
            build: |
              yarn build
              strip -x *.node
          - host: windows-latest
            build: yarn build
            target: x86_64-pc-windows-msvc
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: |-
              set -e &&
              yarn build --target x86_64-unknown-linux-gnu &&
              strip *.node

    name: build and test - ${{ matrix.settings.target }} - node@latest
    runs-on: ${{ matrix.settings.host }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          check-latest: true
          cache: yarn

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
          target: ${{ matrix.settings.target }}

      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/
            ~/.cargo/git/
            packages/absence-router/.cargo-cache/registry/index/
            packages/absence-router/.cargo-cache/registry/cache/
            packages/absence-router/.cargo-cache/git/db/
            packages/absence-router/target/
          key: ${{ matrix.settings.target }}-cargo-registry

      - name: Cache npm dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build bindings
        working-directory: packages/absence-router
        run: ${{ matrix.settings.build }}
        shell: bash

      - name: Build packages
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bindings-${{ matrix.settings.target }}
          path: packages/absence-router/router.*.node
          if-no-files-found: error

      - name: Test bindings
        run: yarn test

  release:
    if: ${{ github.event_name == 'pull_request_target' && github.event.label.name == 'auto-merge' }}

    name: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          check-latest: true
          cache: yarn

      - name: Cache npm dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: packages/absence-router/artifacts

      - name: Move artifacts
        run: yarn workspace @absence/router artifacts

      - name: Run prettier
        run: |
          yarn prettier --write .
          git diff --quiet && git diff --staged --quiet || git commit -am 'style: auto format'

      - name: Publish
        run: |
          yarn version check
          yarn version apply
          yarn workspaces foreach --since=origin/main npm publish --access public

      - name: Push
        env:
          BASE_BRANCH: ${{ github.base_ref }}
        run: |
          git checkout main
          git merge --squash ${BASE_BRANCH}
          git commit
          git push origin main
