name: build-test

env:
  DEBUG: napi:*
  MACOSX_DEPLOYMENT_TARGET: "10.13"

"on":
  pull_request:
    branches:
      - dev
      - main
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"

jobs:
  build-test:
    strategy:
      fail-fast: true

      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
            build: |
              pnpm build
              strip -x *.node
          - host: windows-latest
            build: pnpm build
            target: x86_64-pc-windows-msvc
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: |-
              set -e &&
              pnpm build --target x86_64-unknown-linux-gnu &&
              strip *.node

    name: build and test - ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          check-latest: true
          cache: pnpm

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
          target: ${{ matrix.settings.target }}

      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/
            ~/.cargo/git/
            packages/absence-router/.cargo-cache/registry/index/
            packages/absence-router/.cargo-cache/registry/cache/
            packages/absence-router/.cargo-cache/git/db/
            packages/absence-router/target/
          key: ${{ matrix.settings.target }}-cargo-registry

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache bindings
        uses: actions/cache@v3
        id: bindings-cache
        with:
          path: packages/absence-router/router.*.node
          key: ${{ runner.os }}-bindings-${{ hashFiles('packages/absence-router/**/*.rs') }}

      - name: Build bindings
        if: steps.bindings-cache.outputs.cache-hit != 'true'
        working-directory: packages/absence-router
        run: ${{ matrix.settings.build }}
        shell: bash

      - name: Build packages
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bindings-${{ matrix.settings.target }}
          path: packages/absence-router/router.*.node
          if-no-files-found: error

      - name: Test bindings
        run: pnpm test

      - name: Check format
        run: pnpm prettier --check .
