name: ci

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "yarn"

      - run: corepack enable

      - run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
        id: yarn-cache-dir-path

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install
        if: steps.cache-primes.outputs.cache-hit != 'true'

      - run: yarn build
      - run: yarn test
