name: release

env:
  DEBUG: napi:*
  MACOSX_DEPLOYMENT_TARGET: "10.13"

"on":
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"

jobs:
  build:
    strategy:
      fail-fast: true

      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
            build: |
              yarn build
              strip -x *.node
          - host: windows-latest
            build: yarn build
            target: x86_64-pc-windows-msvc
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: |-
              set -e &&
              yarn build --target x86_64-unknown-linux-gnu &&
              strip *.node

    name: build - ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          check-latest: true
          cache: yarn

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
          target: ${{ matrix.settings.target }}

      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/
            ~/.cargo/git/
            packages/absence-router/.cargo-cache/registry/index/
            packages/absence-router/.cargo-cache/registry/cache/
            packages/absence-router/.cargo-cache/git/db/
            packages/absence-router/target/
          key: ${{ matrix.settings.target }}-cargo-registry

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Cache bindings
        uses: actions/cache@v3
        id: bindings-cache
        with:
          path: packages/absence-router/rotuer.*.node
          key: ${{ runner.os }}-bindings-${{ hashFiles('packages/absence-router/**/*') }}

      - name: Build bindings
        if: steps.bindings-cache.outputs.cache-hit != 'true'
        working-directory: packages/absence-router
        run: ${{ matrix.settings.build }}
        shell: bash

      - name: Build packages
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bindings-${{ matrix.settings.target }}
          path: packages/absence-router/router.*.node
          if-no-files-found: error

  release:
    name: release
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          check-latest: true
          cache: yarn

      - name: Cache npm dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: packages/absence-router/artifacts

      - name: Move artifacts
        run: yarn workspace @absence/router artifacts

      - name: Build packages
        run: yarn build

      - name: Publish
        run: |
          yarn version check
          yarn version apply --all ${{ (github.ref_name == 'dev' && '--prerelease') || '' }}
          yarn workspaces foreach --no-private npm publish --tolerate-republish --access public
        env:
          YARN_NPM_AUTH_TOKEN: "${{ secrets.NPM_AUTH_TOKEN }}"

      - name: Commit changes
        id: autocommit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Sagnik Pradhan
          author_email: contact.sagnikpradhan@gmail.com
          push: "--force"
          message: "Release"
